### PR TITLE
F1155 channels 43437, 43439, 40015, 40016 added

### PR DESCRIPTION
**Pull request by yozik04**
Added a must have channels for F1155.

HM-pump speed, Brine Pump Speed, Brine in temperature, Brine out temperature.

### CODE REVIEW

**Comment by alexf2015** [comment]
Thanks for your contribution. Please

1) remove 43437, it has already been moved to the base channels and thus is available for all models
2) please check if channel 44270 ( Calculated Cooling Supply Temperature S1 ) is also available for model F1155. It has recently been added for F1145 so I guess it is also available for F1155.

Thanks
Alex

**Comment by yozik04** [comment]
I do not have cooling available in my model. As Iunderstood it requires some additional modules to make it available.

**Review by alexf2015 — CHANGES_REQUESTED** [review]
Ok then please just remove "f1155-type-43437"

**Comment by yozik04** [comment]
Done.

**Comment by yozik04** [comment]
Wait a second. Something wrong is here. Where should this channel go. To compressor or generic?

**Comment by yozik04** [comment]
Now it is right and working.

**Comment by yozik04** [comment]
For F1255 base-type-47041 "Hot water mode" has also option 4 (smart control).
I do not know if other systems have it.

Should I add it?

**Review by alexf2015 — APPROVED** [review]

**Pull request merged**
